name: Web API Deploy Pipeline
on:
  push:
    paths:
      - ".github/workflows/**"
      - "cicd-section/api/**"

env:
  AWS_REGION: ap-northeast-1
  ECR_CLUSTER: my-app-clusterr
  ECR_SERVICE: my-app-api-service
  ECR_REPOSITORY: my-app-api
  ECR_TASK_DEFINITION_API: cicd-section/.aws/task-def-api.json

permissions:
  id-token: write
  contents: read

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: cicd-section/api
    steps:
      - uses: actions/checkout@v6

      - name: Run Tests and Build an Image
        run: docker image build -t temp_api_image:latest .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-region: ${{env.AWS_REGION}}
          role-to-assume: ${{secrets.AWS_ROLE_TO_ASSUME}}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Push the image to Amazon ECR
        env:
          ECR_REGISTRY: ${{steps.login-ecr.outputs.registry}}
        run: |
          docker image tag temp_api_image:latest $ECR_REGISTRY/$ECR_REPOSITORY:${{github.sha}}
          docker image push $ECR_REGISTRY/$ECR_REPOSITORY:${{github.sha}}
          echo $ECR_REGISTRY/$ECR_REPOSITORY:${{github.sha}} > api-image-uri.txt

      - name: Upload the image uri file as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: api-image-uri
          path: cicd-section/api/api-image-uri.txt

  deploy:
    runs-on: ubuntu-latest
    needs: [test-and-build]

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-region: ${{env.AWS_REGION}}
          role-to-assume: ${{secrets.AWS_ROLE_TO_ASSUME}}

      - name: Dowonload the artifact
        uses: actions/download-artifact@v5
        with:
          name: api-image-uri
          path: artifacts

      - name: Define the image uri
        run: |
          echo "API_IMAGE_URI=$(cat artifacts/api-image-uri.txt)" >> $GITHUB_ENV

      - name: Fill in the new image URI in the amazon ECS task definition
        id: render-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ${{env.ECR_TASK_DEFINITION_API}}
          container-name: api
          image: ${{ env.API_IMAGE_URI }}

      - name: Deploy ECS task
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.render-task-def.outputs.task-definition }}
          service: ${{env.ECR_SERVICE}}
          cluster: ${{env.ECR_CLUSTER}}
          wait-for-service-stability: true
